### ISSUE TITLE
geo-referenced coordinates

### ISSUE THREAD

**Issue by andreas-wuestefeld** [DAS-RCN/DAS_metadata#1]
reading through the whitepaper it is not clear how the distinction between channels, cable distance and geographical coordinates is incorporated
It may be useful to have a dedicated section on coordinates somewhere with
- channel number /ID
- channel spacing dx
- channel distance to interrogator (optical distance)
- geo-referenced coordinates (after tap test corrections), 
    - X,Y,Z 
    - optionally lat,long
  
this info seems to be all in there, but a bit scattered. However this seems one of the most critical information in the data, so it might deserve a more prominent position

**Comment by vhlai-seis** [comment]
Noted and will be incorporated in the new attribute structure.
