### ISSUE TITLE
Misspelling

### ISSUE THREAD

**Issue by speleos** [DAS-RCN/DAS_metadata#17]
https://github.com/DAS-RCN/DAS_metadata/blob/2fc504b5fc1daab9750ac00a33981db18fd1937d/template/example_poro.json#L7C9-L9C50

Shouldn't it be "Principal Investigator"?

**Comment by vhlai-seis** [comment]
Yes. Thanks for pointing it out. I have updated the term (and confirmed that it is correct under overview.md) .
