### ISSUE TITLE
Repeated information

### ISSUE THREAD

**Issue by speleos** [DAS-RCN/DAS_metadata#18]
https://github.com/DAS-RCN/DAS_metadata/blob/aa6509df2b8070b9fea579781ed0dfbca7f9d5e5/template/example_poro.json#L409

If Fiber is already linked to Cable, why is cable_id necessary again?

**Comment by speleos** [comment]
The same also happens in Acquisition, where interrogator_id is repeated

**Comment by vhlai-seis** [comment]
Thanks for your questions.   

Current rationale:
> If Fiber is already linked to Cable, why is cable_id necessary again?

A cable may contain multiple fibres. Most of the time we might use different cables (for different fibres), but the metadata is designed to capture as many scenarios as possible.

> The same also happens in Acquisition, where interrogator_id is repeated

The same interrogator may have multiple acquisitions. 

Lastly, although there is a implicit nesting (i.e. acquisition under interrogator), the ids are repeated for check n balance. We will take note of this feedback and will consider it in future updates.
