### ISSUE TITLE
json example

### ISSUE THREAD

**Issue by andreas-wuestefeld** [DAS-RCN/DAS_metadata#2]
the structure of the meta data makes it seem very suitable for json format
This could also be easy to read in various other code, and exported if the meta data is used as header in a file format (e.g. miniDAS https://github.com/DAS-RCN/RCN_DASformat)

**Comment by miili** [comment]
Check out https://json-schema.org/ for a formalizing format for JSON.

**Comment by vhlai-seis** [comment]
Will look into JSON. keep you all posted.
