### ISSUE TITLE
Define cable mapping

### ISSUE THREAD

**Issue by dbpodrasky** [DAS-RCN/DAS_metadata#6]
## Request new feature

* Short description of new feature: EPSG designators
* Submitter: David Podrasky, Silixa LLC

Feature request (reason, suggestion to implement):

Coordinate system descriptions are too vague. If provided in meta-data, geodetic or projected coordinate systems should be fully defined by things like horizontal datum, vertical datum, ellipsoid, units, projection, zone, etc. EPSG codes exist for this purpose and propose that they be required when including any sensing cable coordinates. Descriptive text is fine too, but EPSG codes should be a requirement.

**Comment by andreas-wuestefeld** [comment]
I fully support this suggestion

**Comment by vhlai-seis** [comment]
@dbpodrasky , thanks for the suggestion. will implement in the updated attributes.
