### ISSUE TITLE
Use Markdown in RFC phase

### ISSUE THREAD

**Issue by miili** [DAS-RCN/DAS_metadata#8]
I want to propose to move the proposal to Markdown instead of a static PDF.

Markdown has the advantage that it can be discussed, edited and revision in an transparent and open fashion. Once the community / owner is happy a Markdown document can be rendered into any format. PDF, HTML, Word, LaTeX or whatever.

For a proper and transparent RFC I advocate strongly for modern Markdown on GitHub.

**Comment by vhlai-seis** [comment]
Hi!  The attribute tables (and terms) from the white paper have been translated and posted in Markdown format.  Since then the attributes has been updated as well.

**Comment by miili** [comment]
There are two sources of truth now, the PDF and a Markdown.

The attributes differ between the two versions. Maybe it is better to have only one Markdown document, with easy, transparent information that allows versioning. Markdown allows building modern static websites as well.

See e.g. http://docs.fdsn.org/projects/stationxml/en/latest/index.html

**Comment by vhlai-seis** [comment]
PDF version has been removed. Github now only host the Markdown document.
